name: timetrakr_in_flutter
description: Simple time-tracking android app. You can use it to get more precise work log times in issue trackers such as Jira or Youtrack. Now in Flutter!

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_repository: ^1.0.0
  flutter_repository_sqflite: ^1.0.2
  flutter_event_projections: ^1.3.1
  emptiable_list: ^1.0.1
  intl: ^0.16.0
  flutter_slidable: ^0.5.4
  animated_stream_list: ^1.1.0
  short_stream_builder: ^0.0.1
  clock: ^1.0.1
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  mockito: ^4.1.1
  sqflite: ^1.1.7+1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true